name: Send Latest Release to Telegram

on:
  workflow_dispatch:

jobs:
  send-release-to-telegram:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Get Latest Release Info
        id: release
        uses: actions/github-script@v7
        with:
          script: |
            const release = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            const assets = release.data.assets.map(asset => asset.browser_download_url).join('\n');

            const message = `📦 *${release.data.name}* (${release.data.tag_name})\n\n` +
                            `${release.data.body || '_No changelog_'}\n\n` +
                            `🔗 *Download Links:*\n${assets}`;

            core.setOutput("message", message);

      - name: Send to Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          MESSAGE: ${{ steps.release.outputs.message }}
        run: |
          curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage \
            -d chat_id="$TELEGRAM_CHAT_ID" \
            -d text="$MESSAGE" \
            -d parse_mode="Markdown"
