name: Downloads Counter

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  run-counter:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN_2 }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install urlwatch
        run: |
          pip install --upgrade urlwatch
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Write config & jobs
        run: |
          mkdir -p ~/.config/urlwatch
          cat <<EOF > ~/.config/urlwatch/urlwatch.yaml
report:
  telegram:
    enabled: true
    bot_token: "${TELEGRAM_BOT_TOKEN}"
    chat_id: "${TELEGRAM_CHAT_ID}"
EOF

          cat <<EOF > ~/.config/urlwatch/urls.yaml
- name: Check downloads count
  url: https://prop.domiadi.com
  filter:
    - css: div.text-sm.opacity-90
    - html2text
    - re: ([0-9]+) downloads
EOF

      - name: Run urlwatch (with fallback Telegram message)
        run: |
          urlwatch > output.txt || true
          if grep -q "NEW:\|CHANGED:" output.txt; then
            cat output.txt
          else
            curl -s -X POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage \
              -d chat_id="${TELEGRAM_CHAT_ID}" \
              -d text="ℹ️ No change in download count detected on prop.domiadi.com"
          fi
