name: Downloads Counter

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  run-counter:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN_2 }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install urlwatch
        run: |
          pip install --upgrade urlwatch

      - name: Write config & jobs
        run: |
          mkdir -p ~/.config/urlwatch
          echo "
report:
  telegram:
    enabled: true
    bot_token: \"$TELEGRAM_BOT_TOKEN\"
    chat_id: \"$TELEGRAM_CHAT_ID\"
" > ~/.config/urlwatch/urlwatch.yaml

          echo "
- name: Check downloads count
  url: https://prop.domiadi.com
  filter:
    - css: div.text-sm.opacity-90
    - html2text
    - re: ([0-9]+) downloads
" > ~/.config/urlwatch/urls.yaml

      - name: Run urlwatch
        run: ~/.local/bin/urlwatch || echo "No changes"
